spring:
<<<<<<< HEAD
  redis:
    url: redis://admin@104.224.130.79:6379
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://104.224.130.79:3306/debbi?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: admin
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
=======
  profiles:
    active: h2
>>>>>>> acd34eb69a5305a84e529b33c1815451c9ba29e9
server:
  port: 9001
