spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/debbi?autoReconnect=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    password: root
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
swagger:
  title: swagger title测试